<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class closecash extends Model
{
    use HasFactory;
    protected $fillable = 
    [
    'x_oneamtSistema', 
    'x_fiveamtSistema', 
    'x_tenamtSistema',
    'x_twentyamtSistema', 
    'x_fiftyamtSistema', 
    'x_hundredamtSistema',
    'yappySistema',
    'otrosSistema',
    'valespagodaSistema',
    'CheckAmtSistema',
    'LotoAmtSistema',
    'CardAmtSistema',
    'CashAmtSistema',
    'CoinRollSistema',
    'InvoiceAmtSistema',
    'VoucherAmtSistema',
    'GrantAmtSistema',
    'x_oneamtFiscalizadora', 
    'x_fiveamtFiscalizadora', 
    'x_tenamtFiscalizadora',
    'x_twentyamtFiscalizadora',
    'x_fiftyamtFiscalizadora',
    'x_hundredamtFiscalizadora',
    'yappyFiscalizadora',
    'otrosFiscalizadora',
    'valespagodaFiscalizadora',
    'CheckAmtFiscalizadora',
    'LotoAmtFiscalizadora',
    'CardValeFiscalizadora',
    'CardVisaFiscalizadora',
    'CardMasterFiscalizadora',
    'CardAEFiscalizadora',
    'CashAmtFiscalizadora',
    'CoinRollFiscalizadora',
    'InvoiceAmtFiscalizadora',
    'VoucherAmtFiscalizadora',
    'GrantAmtFiscalizadora',
    'totalPanaderiaFiscalizadora',
    'totalPagatodoFiscalizadora',
    'totalsuperFiscalizadora',
    'dineroTaxiFiscalizadora',
    'vueltoMercadoFiscalizadora',
    'comentariosFiscalizadora',
    'x_oneamtGerente', 
    'x_fiveamtGerente', 
    'x_tenamtGerente',
    'x_twentyamtGerente', 
    'x_fiftyamtGerente', 
    'x_hundredamtGerente',
    'yappyGerente',
    'otrosGerente', 
    'valespagodaGerente', 
    'CheckAmtGerente',
    'LotoAmtGerente', 
    'CardValeGerente', 
    'CardVisaGerente',
    'CardMasterGerente',
    'CardAEGerente',
    'CashAmtGerente',
    'CoinRollGerente',
    'InvoiceAmtGerente',
    'VoucherAmtGerente',
    'GrantAmtGerente',
    'totalPanaderiaGerente',
    'totalPagatodoGerente',
    'totalsuperGerente',
    'dineroTaxiGerente',
    'vueltoMercadoGerente',
    'comentariosGerente',
    'DateTrx',
    'AD_Org_ID',
    'valeAmt',
    'valeAmtFiscalizadora',
    'valeAmtGerente'
    ];
}
